steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      '-c', 'docker build
        -f deployments/staging/Dockerfile-staging
        --no-cache
        .
      '
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/traefik']

  - name: 'gcr.io/google-containers/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl apply -f deployment.yml

options:
  logging: CLOUD_LOGGING_ONLY

# Specify the service account
serviceAccount: projects/${_PROJECT_ID}/serviceAccounts/${_SERVICE_ACCOUNT_EMAIL}