apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
        - name: traefik
          image: gcr.io/soy-vision-433708-i2/traefik:latest
          args:
            - "--configFile=/etc/traefik/traefik.yml"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/traefik
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: traefik-config

---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: traefik
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  traefik.yml: |
    entryPoints:
      web:
        address: ":80"
      traefik:
        address: ":8080"

    providers:
      kubernetesGateway:
        endpoint: "http://34.132.103.142:8080"

    api:
      dashboard: true
      insecure: true

    log:
      level: DEBUG

    experimental:
      plugins:
        jwt-validation-middleware:
          moduleName: "github.com/legege/jwt-validation-middleware"
          version: "v0.2.1"