entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

providers:
  file:
    filename: ./dynamic_conf.yml
    watch: true

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

experimental:
  plugins:
    jwt-validation-middleware:
      moduleName: "github.com/legege/jwt-validation-middleware"
      version: "v0.2.1"