steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      '-c', 'docker build
        -t us-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}:$BRANCH_NAME-$SHORT_SHA
        -t us-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}:latest
        -f deployments/staging/Dockerfile
        --no-cache
        .
      '
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/traefik']

  - name: 'gcr.io/google-containers/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl apply -f deployment.yml

options:
  logging: CLOUD_LOGGING_ONLY

# Specify the service account
serviceAccount: projects/${_PROJECT_ID}/serviceAccounts/${_SERVICE_ACCOUNT_EMAIL}

substitutions:
  _PROJECT_ID:           soy-vision-433708-i2                             # Project ID
  _K8S_CLUSTER:          cluster                                  # K8s cluster name
  _NAMESPACE:            default                                  # K8s namespace
  _REPOSITORY:           cery-images                              # Artifact Registry repository name
  _SERVICE_ACCOUNT_EMAIL: 334125085194-compute@developer.gserviceaccount.com