entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

providers:
  kubernetesGateway:
    endpoint: "http://34.132.103.142:8080"

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

experimental:
  plugins:
    jwt-validation-middleware:
      moduleName: "github.com/legege/jwt-validation-middleware"
      version: "v0.2.1"